# Site settings
title: "WANGSHUO'S BLOG"
description: "the blog of wangshuo."
keywords: "blog, wangshuo, jekyll"
baseurl: ""
url: "http:////uestcshuo.github.io"
highlighter: pygments
paginate: 5
author:
    name: wangshuo
    github: uestcshuo
    email:
    gitcafe: 
    twitter:
    facebook:
    googleplus:
    weibo: 
qiniudn:                 # //{bucket}.qiniudn.com
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

# comment
comments:
    duoshuo:
        name:                                # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid: uestcshuo                            # 百度统计 js 代码后的字符串

# blogroll
blogroll: true
brlist:
    - text: "Wangshuo's Space"
      url : //uestcshuo.github.io/
